[package]
name = "http-example"
version = "0.1.0"
authors = ["erkin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
reqwest = { version = "0.10"}
tokio = { version = "0.2", features = ["full"] }